### ISSUE TITLE
Is if possible to provide data which has non-Euclidean distance metric?

### ISSUE THREAD

**Issue by sambitdash** [peterwittek/Somoclu.jl#10]
I have a dataset that requires a custom distance metric and is a city block distance with a variation. Is it possible to model it in the Somoclu framework? I saw the only possible way to pass such a parameter was with data parameters which are essentially just float arrays.

**Comment by peterwittek** [comment]
This is a great question in the context of the Julia wrapper. At low level, the distance functions are calculated in [`mapDistanceFunctions.cpp`](https://github.com/peterwittek/somoclu/blob/master/src/mapDistanceFunctions.cpp), and somewhat redundantly, in [`uMatrix.cpp`](https://github.com/peterwittek/somoclu/blob/master/src/uMatrix.cpp). Since you can't pass a C/C++ function from Python or R, I found no reason to change this behaviour. If I recall correctly, Julia lets us pass such functions.

If you are interested in this, I can make the necessary changes in the backend to receive an arbitrary distance function from Julia. In turn, I would like to ask you to take care of the Julia part of passing a distance function, with a matching test.

**Comment by sambitdash** [comment]
It will be great if you can do so. I will take care of the Julia part. Essentially, data should be a parametric type and distance is on a metric of this parametric data type.

**Comment by peterwittek** [comment]
I took a second, closer look. Unfortunately the situation is not so rosy, since the BMUs are also calculated with the Euclidean distance. This is actually where the whole acceleration happens. Give me a few minutes to see whether it makes sense to have a separate handling mechanism for Julia.

**Comment by peterwittek** [comment]
About the data type, it is float32 because of the GPU acceleration.

**Comment by sambitdash** [comment]
I see. I guess we have hit a limitation in that case. Let me try implementing a simple Julia version for my specific use case. I have relatively smaller data set so may not require a very fast execution time.

**Comment by peterwittek** [comment]
It's been a while since I worked on this. I realized that there are two distances:

1. Distance between codebook vectors and data instances. This is Euclidean.
2. Distance between coordinates on the SOM. This is Euclidean, but it factors in the topology of the map (planar vs toroid, rectangular vs hexagonal).

The second is straightforward to change to an arbitrary function. The first one is somewhat trickier, but it can be done in the CPU version. Which one did you have in mind?

**Comment by sambitdash** [comment]
Second does not have to change as in the mapped space entities can be in the Euclidian metric. The data can be in the non-Euclidean metric.  So guess in my use case it's the first one where there is the challenge.

**Comment by sambitdash** [comment]
I can transform my data to array of floats. But guess only the distance metric should be customizable.

**Comment by peterwittek** [comment]
I am working on it. Some long-overdue cleaning has already been done (see the commits in somoclu). Give me an hour. In the meantime, please look into how you can pass the distance function from Julia.

**Comment by peterwittek** [comment]
Back-end changes are done. The function `julia_train` in somoclu can now be modified to take a distance function from Julia.

**Comment by sambitdash** [comment]
Wow. You are blazing fast as your code is!!! I work out of India so my workday may get to an end soon. If I cannot close it today I will work on it tomorrow.

**Comment by sambitdash** [comment]
I guess the `julia_train` method does not have the callback exposed. However, I have made some changes to the signature to accommodate the same. They can be seen [here](https://github.com/peterwittek/somoclu/compare/master...sambitdash:master).

Somehow, the callback from the SO into Julia is crashing Julia. I have no clear understanding yet as why this may be happening. May need a few iterations as I complete the task. Once I am done, I will send the PRs.

**Comment by peterwittek** [comment]
Thanks. I indeed forgot to add it to the call signature. Please remove the printf calls when you send a PR, otherwise the R community will slaughter us.

**Comment by sambitdash** [comment]
Definitely. It was only to check race conditions. Julia callbacks have serious thread safety issues.

**Comment by peterwittek** [comment]
Talking about callbacks crashing Julia, even simple data types like a string can do random crashes. I never figured out why. The very reason why there is a separate function in Somoclu to interface with Julia goes back to this. I hope you will have more luck.

**Comment by sambitdash** [comment]
I think I have delved in deeper into the issue. But Julia with OpenMP really does not make sense as the callbacks have to compute in one thread. Yet, I have written some code. Once I am done I will check-in for review. We will decide if we want to move forward in that directions.

**Comment by sambitdash** [comment]
I think I have made some changes for the non-OpenMP version and made it to work properly. The OpenMP version though developed does not work properly so has been commented out at places. Both sets of WIP code are checked in.

**Comment by peterwittek** [comment]
I can see the changes in Somoclu, but not in .jl. I would never have been made such complex changes, thanks. I have some comments:

- Can we move [these](https://github.com/peterwittek/somoclu/compare/master...sambitdash:master#diff-70d2146d4d2d605901aa0db04079e29cR178) declarations to `julia.cpp`? They are only used there.
- I would rather create a julia targe in `Makefile.in` instead of [this](https://github.com/peterwittek/somoclu/compare/master...sambitdash:master#diff-4462a3643e734e99564bb783c77aa58dR39). If we can tell `build.jl` to build only this target, then we also don't need a modified copy of `somoclu.cpp` in `Somoclu.jl`.

What do you think?

**Comment by sambitdash** [comment]
Makes sense. I can fix that. Actually, all Julia dependent APIs can be moved to julia.cpp to the beginning. The proposed change to Somoclu.cpp is very minimal though and ideally should be included. It just states in the MINGW env `unistd.h` and `getopts.h` are not in the Windows directory.

**Comment by peterwittek** [comment]
Yeah, that's what I was thinking: move all Julia-related stuff to a single file. I agree that the change to `somoclu.cpp` is minimal, but a new make target would be a more elegant solution.

**Comment by sambitdash** [comment]
@peterwittek, I guess I have made all the necessary features needed to make the code work with Julia. Please review the check-ins in: [https://github.com/sambitdash/somoclu](https://github.com/sambitdash/somoclu). The Julia connector can be found [here](https://github.com/sambitdash/somoclu.jl). 

## Major Changes
1. Julia code integrates seamlessly with OpenMP as well as non-OpenMP versions.
2. All multi-threading handling of OpenMP threads are managed in the .so. Only one call to compute the distance is carried out as a callback from C/C++ into Julia. Julia has serious restrictions on calling back into the native code when you are in a callback in the Julia layer. However, practically this ensures `get_distance` is computed in one master thread.  
3. Pre-processor statements were eliminated at places as they were affecting the readability of the code. For example, CLI preprocessor can be easily replaced with a generic `archiver` structure. 
4. Same Euclidean metric example was used but the method is overwritten in the `test` directory with a Julia code. 
5. New build targets are modified / added. 

Pls. review and if you have any concerns and revert back to me.

**Comment by peterwittek** [comment]
I changed the code back to `libsomoclu.so` as the last commit in somoclu merges the Julia target with the lib target.

Do we still need `somoclu.cpp`? It is definitely out of sync with the main library, and the lib target does not need it anyway.

I am super-naive about this, but the wizardry that goes on in `Makefile.libsomoclu.mingw` looks to me as if we could achieve the same effects with the stock Makefile plus environment variables. What do you think?

**Comment by sambitdash** [comment]
MingW does not have `autoconf` at least in the repository WinRPM uses. So if you want to use that env. you need a `Makefile` or sorts. That's what I did to make it work for Windows. It does not even have a `make` command. So I had to download that from the GNUWin32 repository. 

In short, you cannot do away with that custom `Makefile.libsomoclu.mingw` as `autoconf` cannot generate  a stock `Makefile` for you.

**Comment by sambitdash** [comment]
Sorry, I don't think both `somoclu.cpp` nor `Makefile.libsomoclu.mingw` are needed in the Julia package. They should be deleted. They are already part of the main `somoclu` package.

**Comment by peterwittek** [comment]
We are on the same page. I am merging your PR for the `Makefile`, and I hope the rest of the Julia interface will be easier to finish. Thanks.

**Comment by sambitdash** [comment]
https://github.com/peterwittek/Somoclu.jl/pull/12 removed the makefile and the cpp file from the deps directory.

**Comment by peterwittek** [comment]
Perfect, thanks. So once you are happy with the boilerplate code in somoclu, we'll release a new of version.

**Comment by peterwittek** [comment]
@sambitdash, how do you feel about the current state of affairs? If you find the current interface reasonable, we will proceed releasing a new version of Somoclu and Somoclu.jl soon. Thanks.

**Comment by sambitdash** [comment]
@peterwittek, the [1.7.5-pre](https://github.com/peterwittek/somoclu/releases/download/1.7.5-pre/somoclu-1.7.4.tar.gz) release does not have many of the files. Can you upload with the correct set of files so that I can make the build scripts work with Somoclu.jl?

**Comment by peterwittek** [comment]
My bad, it was there to test the conda-forge built. I updated the file.

**Comment by peterwittek** [comment]
The release is pretty much ready. I updated the tar.gz in the pre-release. Note that [this commit](https://github.com/peterwittek/somoclu/commit/d477b4f490cb4cc9f5bdce5cd6fd056245d3130b) changes the Julia interface to make the OpenMP import conditional. Otherwise compilation fails on macOS.

We proceed with the new release once we have the green light from you.Thanks.

**Comment by sambitdash** [comment]
I will test it in next 4-5 hours and update you.

**Comment by sambitdash** [comment]
The somoclu-1.7.4 does not have the file: `Makefile.libsomoclu.mingw` without that the Windows build will not proceed.

**Comment by peterwittek** [comment]
My bad. I updated the make dist target and the tar.gz. Please try again.

**Comment by sambitdash** [comment]
Please merge: https://github.com/peterwittek/somoclu/pull/110 and then regenerated the tar.gz file. Then merge https://github.com/peterwittek/Somoclu.jl/pull/13 

That should fix all the merge issues.

**Comment by peterwittek** [comment]
To me it looks like the Windows build fails on something that is unrelated to Somoclu.jl. Could you take a look at the [AppVeyor report](https://ci.appveyor.com/project/peterwittek/somoclu-jl)? Thanks.

**Comment by sambitdash** [comment]
There seems to be a download failure. Please issue a rebuild.

**Comment by sambitdash** [comment]
Seems sourceforge is in DR mode and does not permit script downloads work properly. So make commands are not getting downloaded properly. Check after sometime.

**Comment by sambitdash** [comment]
[AppVeyor Report](https://ci.appveyor.com/project/sambitdash/somoclu-jl) passed.

**Comment by peterwittek** [comment]
Awesome! Thank you so much for all your insight, help, and contribution. The release is in progress.

**Comment by sambitdash** [comment]
You are most welcome @peterwittek .

**Comment by Tortoise17** [comment]
Dear @ Peterwittek and Sambitdash.

Thank you .. nice discussion. I have to ask that is this code now working for non-euclidean distance too? I mean if there is any option which I can use based on python. 

Please help if any possibility.

**Comment by sambitdash** [comment]
@khawar85 The intent of my work was to make sure you can define your distance function in Julia. If you can do that you can virtually decide whichever metric you want to use (Euclidean or non-Euclidean). That works now from Julia. Not sure if that interface has been exposed in Python. Will wait for @peterwittek to respond. 

@khawar85 do you know if Python supports callbacks from C/C++?

**Comment by peterwittek** [comment]
To my knowledge, there is no straightforward way for doing Python callbacks from C/C++. Extremely cumbersome ways exist that either involve a thousand lines of scaffolding or Cython, but then it is easier to change the function directly in the C++ code. This is why callbacks are a Julia-only feature.

**Comment by Tortoise17** [comment]
Is there any easy solution for this??
and if there is already implemented, is there any example script how I can run in this C++ based approach?

**Comment by peterwittek** [comment]
It depends on your definition of 'easy'. The cheapest solution is to rewrite the Euclidean distance function to the distance you want (lines 29-34 in `denseCpuKernels.cpp`), then recompile the Python version with `make python`.
