### ISSUE TITLE
Windows build

### ISSUE THREAD

**Issue by peterwittek** [peterwittek/Somoclu.jl#2]
...and matching Travis check.

**Comment by jul1278** [comment]
Hi all, I've spoken with Peter over email and I'm going to be having a go at this. Welcome any advice/suggestions/etc on how I should proceed, otherwise I'll probably start looking into python library build.

**Comment by xgdgsc** [comment]
I haven' t seen any julia project that has windows travis running. I think you should first read the [Bindeps Doc](https://github.com/JuliaLang/BinDeps.jl) and try to build at your windows machine.

**Comment by jul1278** [comment]
So just a quick update, I've managed to build a dll with the mapDistanceFunctions code and successfully call ```getWeight(...)``` from the julia shell. 

Also as far as I can tell, travis doesn't support windows yet.

**Comment by peterwittek** [comment]
Wow, that was amazingly fast! Can you run the test?

Both of you are right, Travis does not support Windows. If you can run the test successfully on Windows, I would be happy to merge your contribution.

**Comment by jul1278** [comment]
![capture](https://cloud.githubusercontent.com/assets/6296394/20866459/7a0d7f3c-ba79-11e6-8213-551bb7d5b0a6.PNG)

how does this look? for some reason my PyPlot got messed up and it took me ages to fix it, finally got it working I think.

**Comment by peterwittek** [comment]
Perfect' This looks exactly what it should look like. Could you send a pull request?

**Comment by jul1278** [comment]
So the test passes and everything works fine when I build the dll in g++ . 
I'm trying to set up at vs build config to build a dll but when I ccall the vs built .dll it fails with a "Could not load library '.../somoclu.dll' error", not quite sure what to do about this but I'll keep at it. 

Other question, how do you tell the Somoclu.jl where to look for the library? atm I'm just putting a hardcoded path to my dll in the ccall method

**Comment by peterwittek** [comment]
The file `deps/build.jl` has to be modified to let [BinDeps](https://github.com/JuliaLang/BinDeps.jl) compile the library and it will also put it at the right place (which is `deps/usr/lib` independent of the platform) when you call `Pkg.build("Somoclu")`.

**Comment by jul1278** [comment]
Haven't had a chance to work on this, (busy week), I think what I should be doing is modifying the Makefile to build a dll on windows, rather than worrying about the visual studio project. That way the user just has to call Pkg.build(...) etc.  

As far as I can tell I need autotools to run configure and make on the makefile? I can't build anything running make in the src directory. Is this correct? 

I think I've managed to get  autotools with MinGW but it seems to be just a bunch of scripts

**Comment by peterwittek** [comment]
I am looking at other wrappers in the package index how they do it. I think you are right, MinGW is the way to go. For instance, take a look at [CDDLib](https://github.com/JuliaPolyhedra/CDDLib.jl/blob/master/deps/build.jl).

**Comment by jul1278** [comment]
Should I be able to run make in the src directory though? I get all sorts or errors "no rule to make..." "no target specified.." etc when I call make. I've tried make in the cygwin shell as well.

**Comment by peterwittek** [comment]
When you issue `Pkg.build("Somoclu")`, it downloads and extracts the source dependency in deps/src/somoclu-1.7.2. If you want to take over manually, you have to run `./configure` in this folder, followed by `make`.

**Comment by jul1278** [comment]
Hey guys, I'm back from being sick/christmas holidays, hopefully get this issue closed soonish... 

I'm getting this error trying to ```Pkg.add("Somoclu")``` ?

```
ERROR: unknown package Somoclu
 in macro expansion at .\pkg\entry.jl:53 [inlined]
 in (::Base.Pkg.Entry.##2#5{String,Base.Pkg.Types.VersionSet})() at .\task.jl:360
 in sync_end() at .\task.jl:311
 in macro expansion at .\task.jl:327 [inlined]
 in add(::String, ::Base.Pkg.Types.VersionSet) at .\pkg\entry.jl:51
 in (::Base.Pkg.Dir.##2#3{Array{Any,1},Base.Pkg.Entry.#add,Tuple{String}})() at .\pkg\dir.jl:31
 in cd(::Base.Pkg.Dir.##2#3{Array{Any,1},Base.Pkg.Entry.#add,Tuple{String}}, ::String) at .\file.jl:48
 in #cd#1(::Array{Any,1}, ::Function, ::Function, ::String, ::Vararg{Any,N}) at .\pkg\dir.jl:31
 in add(::String) at .\pkg\pkg.jl:100
```

**Comment by peterwittek** [comment]
This is because Somoclu.jl is not yet merged with the Julia package repository. Installation has to be done as written in the Readme. Our [first milestone](https://github.com/peterwittek/Somoclu.jl/milestone/1) is to bring this package to a level where we have a chance to be included in the official repository. Part of that is resolving this very issue, so your contribution is highly valuable.

**Comment by jul1278** [comment]
Alright, sorry It's taking a while, I realise now I'm a bit out of my depth here. Here are the tasks as I see them:

- modify somoclu source code to expose functions to window .dll 
Basically done, I can compile the somoclu.dll in gcc with a simple command line and successfully run the tests from julia

These are the tasks I'm having trouble with:

- Add a configuration to the makefile which actually builds the windows DLL
I thought the best place to start would be to try to run the ```autogen.sh``` and ```configure``` which requires a sort of unix environment (MinGW/Cygwin). I think I've set these up incorrectly though as I'm getting a variety of errors when I try to run ```autogen.sh```

```
$ autogen.sh
+ test -d Tools/config
+ aclocal -I Tools/config
      0 [main] perl 9568 fork_copy: linked dll data/bss pass 0 failed, 0x72E000..0x74E794, done 0, windows pid 4116, Win32 error 487
      0 [main] perl 7896 fork_copy: linked dll data/bss pass 0 failed, 0xE9E000..0xEBE794, done 0, windows pid 4156, Win32 error 487
```

I'm looking into this ^^ now.


- modify Build.jl to add a build process for windows

**Comment by peterwittek** [comment]
I think this is a good plan. I have zero insight on what the problem could be with aclocal. Sorry about that.

**Comment by jul1278** [comment]
Alright I'm not entirely sure how I did it but I eventually got my environment set up properly, so the next step is to add a configuration to the makefile to build the dll.

**Comment by jul1278** [comment]
Ok, I've managed to get the makefile to build the dll which I can successfully run the example in the readme

**Comment by peterwittek** [comment]
This is with Somoclu proper, right? Could you send a pull request there?

**Comment by blegat** [comment]
The easiest way to get windows build working is to use opensuse build service. For instance, for cddlib, I am using [this spec file](https://build.opensuse.org/package/view_file/home:blegat/cddlib/cddlib.spec?expand=1).
The `dll` are cross-compiled for Windows on an opensuse server automatically and you can use them using WinRPM.
The fist step would maybe be to make a working build script for Linux (see here for many examples: https://build.opensuse.org/project/show/science) and then adapt it to Windows (typically by adding `_mingw64_` at the beginning of each command).

**Comment by jul1278** [comment]
Why would that be better given that we already have a working build for linux and 90% of a working build for windows?

Peter I'll see if I can submit a PR for somoclu proper tonight

**Comment by peterwittek** [comment]
Thanks.

**Comment by blegat** [comment]
@jul1278 I think it is better in the long term since it is built automatically and you do not need to do a manual build for each new version and that is the way Tony Kelman suggests to do it. However, if you are almost done, it is probably not worth the effort. For CDDLib I got help for Jan Engelhardt, otherwise, I agree that adding the support in the opensuse build system might take a rather long time.

**Comment by jul1278** [comment]
Peter I've forked somoclu and pushed my changes for the windows build, just need to clone it onto my macbook and check I haven't broken the unix build, hopefully get a chance to do that tomorrow.

**Comment by peterwittek** [comment]
I took a quick glimpse and it fails on Linux. I commented on your commit to highlight why.

**Comment by jul1278** [comment]
Ok, on my end it's building on mac and windows

**Comment by peterwittek** [comment]
I tried and it builds fine on Linux too in every possible combination (GCC, MPI, CUDA). Please send a pull request.

**Comment by peterwittek** [comment]
Travis builds the Linux and macOS versions without problems. Once we confirm that the new Windows build procedure works fine with the Python flavour, we can release a new version of Somoclu and close this. Many thanks!

**Comment by peterwittek** [comment]
In the meantime, could you check if the Windows version builds as it should? Delete Somoclu from Julia, and try to install it from scratch:

```julia
Pkg.clone("https://github.com/peterwittek/Somoclu.jl")
Pkg.build("Somoclu")
using Somoclu
```
Thanks.

**Comment by xgdgsc** [comment]
I checked with above commands and the example from readme.md. I got error:
```
julia> train!(som, data);
ERROR: UndefVarError: libsomoclu not defined
 in #train!#3(::Int64, ::Int64, ::Int64, ::String, ::Float64, ::Float64, ::String, ::Function, ::Somoclu.Som, ::Array{Float32,2}) at C:\Users\gsc\.julia\v0.5\Somoclu\src\Somoclu.jl:154
 in train!(::Somoclu.Som, ::Array{Float32,2}) at C:\Users\gsc\.julia\v0.5\Somoclu\src\Somoclu.jl:98

```

**Comment by jul1278** [comment]
I'll hopefully get around to the Julia side in the next few days

**Comment by jul1278** [comment]
So I've tried modifying the Build.jl so when on windows we pass in :Windows instead of :Unix or whatever. 
which fails to build. 

I suspect the problem might be because when I build libsomoclu from the command line I actually have to make the ```Tools\config``` folder and then call ```autoconf -v``` not entirely sure what that command does but it seems to work, so I'm thinking I'd need to add those commands to ```autogen.sh``` and have them called on windows os, if possible. 

Is there some way I can test Build.jl with local sources? I see there's an issue on the bindeps repo but it doesn't look like any progress has been made on it.

**Comment by peterwittek** [comment]
This is really weird. I have no idea why you would need an extra call to `autoconf` on Windows. 

If you copy the modified source files in `deps/downloads/somoclu-1.7.3-pre.tar.gz`, it will not download it from GitHub, but use the file there when you call `Pkg.build('Somoclu')`.

**Comment by jul1278** [comment]
so you mean ```.julia/v0.5/Somoclu/deps/downloads/``` ? 

should the link in build.jl remain the same?

**Comment by peterwittek** [comment]
Yes, that is the folder. You can leave the link in `build.jl` as it is.

**Comment by jul1278** [comment]
So when I extract ```somoclu-1.7.3-pre.tar.gz``` it doesn't contain ```autogen.sh``` is that correct?

**Comment by peterwittek** [comment]
It should. Run `make dist` in the Somoclu folder to generate it the correct zip. Then extract it, rename the extracted folder `somoclu-1.7.3` to `somoclu-1.7.3-pre`, and zip it again to get the correct file.

**Comment by jul1278** [comment]
my download of ```https://github.com/peterwittek/somoclu/releases/download/1.7.2/somoclu-1.7.3-pre.tar.gz``` does not contain ```autogen.sh```

**Comment by peterwittek** [comment]
That is right, I think it should not contain autogen.sh, only the generated files. This is a source distribution and not a zip of the git repo.

**Comment by jul1278** [comment]
so what commands should I use to build?

**Comment by peterwittek** [comment]
I lost you a bit. If you put this zip file to the folder mentioned above, `Pkg.build('Somoclu')` extracts it and compiles it.

**Comment by jul1278** [comment]
Yep, so I'm trying to debug why ```Pkg.build()``` fails. 

I'm assuming ```Pkg.build()``` calls ```configure``` and ```make``` etc?

**Comment by peterwittek** [comment]
Yes. This is what is specified in line 8 of `deps/build.jl`.

**Comment by jul1278** [comment]
So what I want to do is extract the .zip file and run the commands that julia will run to build to see where it fails, but if there is no ```autogen.sh``` then I'm not sure how I can do that.

**Comment by peterwittek** [comment]
Could you tell me the exact steps you are doing? I don't see how `autogen.sh` plays any role in this. On Linux, I would do something like this:

1. Delete the existing installation:
```bash
rm -fr ~/.julia/v0.5/Somoclu
```
2. Clone it again from Julia:
```julia
Pkg.clone('https://github.com/peterwittek/Somoclu.jl')
```
3. Make a source distribution from the modified Somoclu (this is to be done in the respective folder).
```bash
make dist
```
4. Unzip the generate file, rename the folder to somoclu-1.7.3-pre, and tar-zip it again.
5. Copy this file to the Julia folder:
```bash
cp somoclu-1.7.3-pre.tar.gz ~/.julia/v0.5/Somoclu/deps/downloads
```
6. Build it in Julia. This will invoke the `configure` script, but not `autogen.sh`.
```julia
Pkg.build('Somoclu')
```
Then every time you make a change in Somoclu, repeat the process from step 3.

**Comment by jul1278** [comment]
Ok, I think I've found the problem, the ```src/Windows``` folder is missing from the zip? I'm guessing ```make dist``` doesn't include it for some reason

**Comment by jul1278** [comment]
I followed those instructions and put the ```src/Windows``` folder inside the zip... still no luck. 

Is there something I can do to the make file (maybe print to the Julia terminal or write a text file somewhere) just so I can be certain that julia is actually trying to build the somoclu inside ```deps/downloads/```?

**Comment by jul1278** [comment]
![image](https://cloud.githubusercontent.com/assets/6296394/22509146/888ef6b6-e8d8-11e6-8573-a496e5c002a3.png)


here's the error

**Comment by peterwittek** [comment]
I don't know. I just tried the above instructions and they work just fine, apart from replacing single quotes by double quotes. I also tried what the error message suggests (`BinDeps.debug("Somoclu")`), but it was not particularly edifying.

**Comment by jul1278** [comment]
Ok, Well I'm not quite sure how to proceed from here. 

If I just add a ```mkdir C:\make_test``` in the makefile inside the .tar.gz, I'll be able to confirm that it is in face the makefile being used?

**Comment by peterwittek** [comment]
You could do that in one of the `Makefile.in` files. The `configure` script will generate the actual makefiles.

**Comment by jul1278** [comment]
So I followed those instructions, added a ```mkdir c:\test``` command in the ```Makefile.in``` and I'm not seeing the folder get created so I'm guessing that the ```downloads\somoclu-1.7.3-pre.tar.gz``` isn't getting used. 

Any other ideas?

**Comment by peterwittek** [comment]
I got hold of a Windows system and I checked it. You are right, nothing is created. I think this is because of `build.jl` says
```julia
libsomoclu = library_dependency("libsomoclu", aliases=["libsomoclu", "libsomoclu.so"], os=:Unix)
```
Julia does not get a clue that it should be the library when it is running on Windows, so when you ask for `Pkg.build("Somoclu")`, nothing happens. So I guess this line has to be extended to account for Windows.

**Comment by jul1278** [comment]
Yes I modified the ```build.jl``` file to be for windows

**Comment by peterwittek** [comment]
Could you push this change to your fork? Then I could try it.

**Comment by jul1278** [comment]
I have pushed the changes to my fork

**Comment by peterwittek** [comment]
Okay, I could replicate the problem, thanks. Unfortunately, I have no clue how to solve it. It fails at the line `@BinDeps.install Dict(:libsomoclu => :libsomoclu)`, but that did not explain why on earth it does not work on Windows.

**Comment by jul1278** [comment]
Can you try to confirm if the ```.tar.gz``` in the downloads folder is the actual source code being used when you call ```Pkg.build("Somoclu")```

I have been unable to do this so far and there's not much point trying to debug the Makefiles etc without proving this

**Comment by peterwittek** [comment]
Yes, but the problem is that on Windows, it does not even try to download the file, or notice its presence if you manually copy it there.

I have an alternative suggestion that bypasses compilation on Windows all together. We always create a binary wheel distribution of the Python interface for Windows and Mac. I think the Windows wheel file includes the DLL that you need. Could you try this?

1. Download the [current wheel file for 64-bit Windows](https://pypi.python.org/packages/25/47/5dd659f0684333ccb794100322d2b28281f27f6040166f5b117f32c9e0de/somoclu-1.7.2-cp35-cp35m-win_amd64.whl).
2. Unzip it. You will see a file called `_somoclu_wrap.cp35-win_amd64.pyd`. Rename this to `libsomoclu.dll`, or whatever the file should be called for Julia, and place it in the Julia folder [where it should be located](https://github.com/peterwittek/Somoclu.jl/issues/2#issuecomment-264771811).
3. Try importing Somoclu in Julia.

If it works, then we could modify `build.jl` to follow the [pattern in Gumbo.jl](https://github.com/porterjamesj/Gumbo.jl/blob/master/deps/build.jl), that is, source build for Unix systems, and binary download for Windows. I won't have access to a Windows computer until Monday the earliest, but you could give it a shot.

Thanks for your tenacity. I hope we can get this right soon.

**Comment by jul1278** [comment]
Ok, I'll give that a try this weekend.

**Comment by jul1278** [comment]
I might go open an issue over on the BinDeps github as well, see if they have any ideas.

**Comment by peterwittek** [comment]
Thanks. I think we can wait with contacting the BinDeps developers: after all, both of us are in the process of learning how to get this right.

**Comment by jul1278** [comment]
I'm not suggesting it's a bug, they might have some advice for debugging builds. 

Also, just an aside, a question about actually using Somoclu, once I've trained an SOM how would I go about retrieving the cluster that an individual training example belongs to? Is that what the codebook is for?

**Comment by peterwittek** [comment]
This is not worked out yet in the Julia version. In Python, the wrapper allows you to run any `sk-learn` clustering algorithm on the codebook, so the best matching units would link cluster membership to data points (see peterwittek/somoclu#66). You could open a new issue here, this should be done for the Julia wrapper too.

**Comment by jul1278** [comment]
Hey sorry I've been AWOL for a few weeks, looking at this again now

**Comment by peterwittek** [comment]
Thanks. I did not make much progress either.

**Comment by jul1278** [comment]
so I am putting libsomoclu.dll (from the pythol wheel) at /.julia/Somoclu/deps/usr/lib/ and then running the command ```import Somoclu``` which results in an error "Somoclu not properly installed... etc etc" 

I comment out the code in Somoclu.jl ```if (isfile(...))``` it runs

When I try to run the sample/test code it error's saying that "Som is not defined" 

How do I tell julia where the .dll is?

**Comment by peterwittek** [comment]
I tried a hundred different locations and filenames, and none of them worked. The folder I recommended came from the [Bindeps](https://github.com/JuliaLang/BinDeps.jl#the-high-level-interface---built-in-providers) documentation. I really don't know what to try next.

**Comment by jul1278** [comment]
Whats the next step here Peter?

**Comment by peterwittek** [comment]
The just released 1.7.3 works fine on Linux and macOS again. I am not sure how to proceed from here with Windows, since I have no experience with the platform. Maybe digging deeper in Bindeps would make a difference.

**Comment by peterwittek** [comment]
@sambitdash, would you take a look at [this comment](https://github.com/peterwittek/Somoclu.jl/issues/2#issuecomment-282241382)? I reckon that the Windows version of the wheel file on PyPI contains the DLL that you would need to make the wrapper work. Thanks.

**Comment by sambitdash** [comment]
@peterwittek I am not sure why this Python wrapper may be needed. I just completed the Julia integration in a Win64 system. Here is the output. 

```
               _
   _       _ _(_)_     |  A fresh approach to technical computing
  (_)     | (_) (_)    |  Documentation: https://docs.julialang.org
   _ _   _| |_  __ _   |  Type "?help" for help.
  | | | | | | |/ _` |  |
  | | |_| | | | (_| |  |  Version 0.6.2 (2017-12-13 18:08 UTC)
 _/ |\__'_|_|_|\__'_|  |  Official http://julialang.org/ release
|__/                   |  x86_64-w64-mingw32

julia> Pkg.test("Somoclu")
INFO: Testing Somoclu
INFO: Somoclu tests passed
julia>
```
The build can be seen at: [https://github.com/sambitdash/Somoclu.jl](https://github.com/sambitdash/Somoclu.jl)

However, 3 pending items remain. 

1. Set the env paths to the gcc as well as post installation libraries (or statically compile with MINGW binaries.)
2. Generalizing the scripts for 32-bit as well as 64-bit. 
3. Cleaning up the WIP code. 

I evaluated many options. 

1. VC Express - Huge runtime download
2. Cygwin or MSYS2 - Both can use `automake` but post compilation binaries had path issues to be loaded into Julia env. I am not sure if there is a fix for it. I saw in the net people complaining about it as well. 

My option:

1. Use WinRPM MINGW installation to build the system.
2. WinRPM does not have a `make` system. Hence, I downloaded it from `GnuWin32` system. Making BinDeps.jl to work is quite cumbersome around this leading to a large monolithic build script. This was my first experience with BinDeps. More than what it can do, you need to know what it does not as there is hardly any documentation particularly around validation checks. 
3. There is no `automake` hence the `Makefile` had to be written again removing all unrelated parts. 
4. There is an assumption `unistd.h` exists as `windows/unistd.h` which is not true for MINGW compiler. Hence, that code was needed to be suitably pre-processed. 

Since, 3 and 4 are related to the C/C++ code, you may want to review and see how you can address it as part of the other project. 

If you are ok with this approach, I will make the 3 pending tasks and send a merge request. You can review the code in my fork for any reviews. 

Sorry, it took a lot longer than I thought or originally planned but guess WinRPM and BinDeps were not easy packages to deal with.

**Comment by peterwittek** [comment]
We always build the binaries for Windows for the Python version. Since it contains the exact same DLL file we need for the Julia version, I thought it would be simpler to use that, rather than going through all the pain you did. It is really impressive, thank you so much.

Regarding 3, unfortunately, using automake is impossible. I tried very hard a few years ago, but it does not allow you to use multiple compilers. This rules out using nvcc. Since the `Makefile.in` is extremely unlikely to change anyway, I would keep the hacked version you created for MINGW.

Regarding 4, I am not sure what to do with it. I reckon that @xgdgsc compiles the Windows code with Visual C++, hence the assumption. Can you specify the make target as `lib` in `build.jl`? If so, this problem does not come up at all. The default make target will compile the library as well as the executable, and only this latter needs `unistd.h`, but it is completely unnecessary for the wrapper.

**Comment by peterwittek** [comment]
PR #7 solves this, although AppVeyor gives an absurd error message.
