### ISSUE TITLE
Please register as a Julia Package.

### ISSUE THREAD

**Issue by sambitdash** [peterwittek/Somoclu.jl#5]
Currently, the package is not registered with Julia as a package. Please update the same.

**Comment by peterwittek** [comment]
Yes, that would be [milestone 1](https://github.com/peterwittek/Somoclu.jl/milestone/1). We have a few pending issues, and I have not used Julia in about a year.

**Comment by peterwittek** [comment]
BTW, if you could help me with the Windows part (issue #2), that would be great. I have zero experience with that platform, and I don't have access to it either.

**Comment by sambitdash** [comment]
Unfortunately, I do not have a native windows system and my trial VM versions would have expired by now. I will give it a shot by downloading again. If it's build and config related I do not think it will be hard to fix but if there is any issue inside specific packages we will reach out to developers of those packages. 

I am assuming you have the necessary C/C++ binaries build on Windows already. If not we may have to work on that as well.

**Comment by sambitdash** [comment]
Was able to get my trial VM up. So I can take a shot at fixing the Windows version.

**Comment by sambitdash** [comment]
With #7 I guess the package is ready to be submitted as a package. You can remove the 0.7 version from Travis and AppVeyor and support 0.6 for now and look at fixing those packages at a later date.

**Comment by peterwittek** [comment]
Thanks a lot for the PR. I am starting the registration process in a bit. I added the AppVeyor badge, but the build fails with an absurd error that cannot possibly be the case. Would you take a look at it in the meantime?

**Comment by peterwittek** [comment]
It's [happening](https://github.com/JuliaLang/METADATA.jl/pull/13156). Many thanks again!

**Comment by sambitdash** [comment]
Fixed the error with #8

**Comment by peterwittek** [comment]
You are a wizard. Thank you so much.

**Comment by sambitdash** [comment]
@peterwittek you are most welcome. Hopefully, you may need some more samples to have a greater coverage in the tests.
