### ISSUE TITLE
Change the license model - GPL3 is too restrictive

### ISSUE THREAD

**Issue by sambitdash** [peterwittek/Somoclu.jl#6]
The package is shared as GPL-3. As most Julia packages are libraries any code which will like to use this package has to develop code to use these APIs. That will make any code used a potential derivative work. That may lead to concerns for commercial development work.

**Comment by peterwittek** [comment]
Good point. I regret for choosing GPL-3 for my other projects, exactly for the points you bring up. Any preference between BSD and MIT licenses?

**Comment by sambitdash** [comment]
I prefer MIT as most Julia projects are MIT and it most compatible to the ecosystem. 

I looked at further details to find the original C/C++ code is developed with GPL-3 as well. In that case packaging the libraries or use the library to install the C/C++ code may be construed as derivative work. Although, there can be deferring views on this interpretation. 

The other approach may be to implement SOM in native Julia with a more permissible license and have Julia handle the optimizations.

**Comment by peterwittek** [comment]
Done. The C/C++ code has Julia-specific parts, and that is under GPL-3. Yet, using this wrapper only needs a binary .so of the GPL-ed code, so I would not look it at as a derived work.

**Comment by sambitdash** [comment]
Derived work is not defined very clearly in GPL and that leads to confusion. However, as the author and owner of the copyright you agree that linking to GPL-ed .so library will not amount to derived work will clearly allow people to use the Julia library without any confusion. Thank you for the quick update.
